In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlibpy import linear_regression as lnr
from mlibpy import logistic_regression as logr
from mlibpy.softmax_regression import *

# Training Dataset

In [3]:
df = pd.read_csv("/datasets/multi_classification_train.csv")
df.head()

ID   Feature_1  Feature_2  Feature_3   Feature_4   Feature_5   Feature_6  \
0   1  -90.532634 -66.953472  79.261856 -111.800554  126.403549  111.509348   
1   2 -103.156720 -16.070400  87.819228   12.614599   51.347780   67.483725   
2   3   24.326153 -92.098078  82.238354  -56.795879   85.203996  127.916504   
3   4  -64.631737 -83.703583  84.135072   -5.516152   74.338494  112.630556   
4   5  -55.473830 -78.853237  88.129107   75.200543   76.991520   60.224711   

    Feature_7   Feature_8   Feature_9  ...  Feature_12  Feature_13  \
0  207.728953  -26.600556 -106.229324  ...  148.391734   77.835738   
1   40.269172   51.442254 -151.486693  ...   29.009475    3.995786   
2  -90.080307 -128.124071   18.036020  ...  111.810098   65.826018   
3  181.576798   -1.054023   60.469865  ...   50.047108  100.439101   
4  -13.106559 -146.773016  -33.490566  ...   85.988282   23.381960   

   Feature_14  Feature_15  Feature_16  Feature_17  Feature_18  Feature_19  \
0  -10.728207    1.100625    1.035362  -87.010809  -16.242297  -32.074925   
1  -10.861630 -142.605726  -25.924592  -86.755351  -36.479749 -130.246619   
2 -101.271203  -44.127749   -7.131464 -105.049759 -130.948256  -43.113523   
3 -117.842955  150.239788 -144.635542 -144.306209  -69.272905  -79.629675   
4   11.876102 -188.296503  -80.323929  -56.757987  -20.314172  -42.625170   

   Feature_20  Class  
0  -17.666026      1  
1  -44.143652      2  
2  -37.330448      4  
3  -51.334456      2  
4  -24.102753      2  

[5 rows x 22 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48000 entries, 0 to 47999
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          48000 non-null  int64  
 1   Feature_1   48000 non-null  float64
 2   Feature_2   48000 non-null  float64
 3   Feature_3   48000 non-null  float64
 4   Feature_4   48000 non-null  float64
 5   Feature_5   48000 non-null  float64
 6   Feature_6   48000 non-null  float64
 7   Feature_7   48000 non-null  float64
 8   Feature_8   48000 non-null  float64
 9   Feature_9   48000 non-null  float64
 10  Feature_10  48000 non-null  float64
 11  Feature_11  48000 non-null  float64
 12  Feature_12  48000 non-null  float64
 13  Feature_13  48000 non-null  float64
 14  Feature_14  48000 non-null  float64
 15  Feature_15  48000 non-null  float64
 16  Feature_16  48000 non-null  float64
 17  Feature_17  48000 non-null  float64
 18  Feature_18  48000 non-null  float64
 19  Feature_19  48000 non-nul

In [7]:
df.describe()

ID     Feature_1     Feature_2     Feature_3     Feature_4  \
count  48000.000000  48000.000000  48000.000000  48000.000000  48000.000000   
mean   24000.500000    -70.377031    -30.146709     86.089425     58.030622   
std    13856.550797     35.625529     64.321876      3.174307    150.228460   
min        1.000000   -207.793134   -275.657994     73.658575   -552.758436   
25%    12000.750000    -93.950289    -74.169885     83.928184    -38.859422   
50%    24000.500000    -70.488932    -34.032790     86.231333     64.003075   
75%    36000.250000    -47.539966     11.762371     88.315934    158.715770   
max    48000.000000     92.716452    251.828102     99.082580    685.645062   

          Feature_5     Feature_6     Feature_7     Feature_8     Feature_9  \
count  48000.000000  48000.000000  48000.000000  48000.000000  48000.000000   
mean      82.418236     77.059309     20.094535     24.109948    -59.318710   
std       20.850338     49.236461     83.548635    105.080878    103.514814   
min       -8.933957   -120.199889   -329.082698   -364.865005   -482.875418   
25%       68.284707     43.466149    -39.753719    -51.267959   -133.005857   
50%       82.336259     77.273308     18.262060     21.571364    -56.711287   
75%       96.570513    110.184213     79.512853     98.345849     14.953232   
max      165.732235    284.008410    384.027585    424.367123    312.741638   

       ...    Feature_12    Feature_13    Feature_14    Feature_15  \
count  ...  48000.000000  48000.000000  48000.000000  48000.000000   
mean   ...     50.870839     72.480118    -63.739069    -70.215822   
std    ...     67.834981     41.586589    104.853085    109.883786   
min    ...   -211.966636    -77.014412   -487.982635   -497.942276   
25%    ...      0.999556     41.953003   -139.293881   -145.792121   
50%    ...     49.878320     71.428007    -65.254980    -74.833671   
75%    ...    100.157070    102.294063     11.157101      3.266465   
max    ...    308.760950    243.734082    317.839985    375.820972   

         Feature_16    Feature_17    Feature_18    Feature_19    Feature_20  \
count  48000.000000  48000.000000  48000.000000  48000.000000  48000.000000   
mean      15.817366    -54.201834    -35.507657    -94.572941    -55.730419   
std       90.129423     59.027953     28.468116     36.119300     26.201795   
min     -371.607846   -281.715471   -158.198302   -253.152360   -164.280348   
25%      -47.466549    -96.935748    -53.733173   -118.808755    -72.284367   
50%       10.801940    -54.326713    -33.399701    -94.628132    -53.243321   
75%       75.648310    -11.113891    -15.863008    -70.081480    -37.329979   
max      376.988432    161.366009     79.463257     46.066815     33.586001   

              Class  
count  48000.000000  
mean       2.048500  
std        1.127427  
min        0.000000  
25%        1.000000  
50%        2.000000  
75%        3.000000  
max        4.000000  

[8 rows x 22 columns]

In [8]:
df.iloc[:, 21].value_counts().sort_index()

Class
0     4040
1    11404
2    16618
3    10064
4     5874
Name: count, dtype: int64

## Training

In [9]:
X_train = np.array(df.iloc[:42000, 1:21])
m, n = np.shape(X_train)
print(m, n)
print(X_train[0,:])
X_train, X_mean, X_std = lnr.normalize(X_train)

42000 20
[ -90.53263395  -66.95347161   79.26185595 -111.80055375  126.40354931
  111.50934762  207.72895316  -26.60055598 -106.22932385  170.38464881
   69.03831992  148.39173402   77.83573824  -10.72820656    1.10062508
    1.0353615   -87.01080867  -16.24229669  -32.07492465  -17.66602617]


In [10]:
y_train = np.array(df.iloc[:42000, 21])
print(np.shape(y_train))
classes = np.unique(y_train)
print(classes)
num_classes = len(classes)
print(num_classes)

(42000,)
[0 1 2 3 4]
5


In [11]:
w = np.random.rand(n, num_classes)
print(np.shape(w))
b = np.random.rand(num_classes)
print(np.shape(b))

(20, 5)
(5,)


In [12]:
yhat_train = predict_softmax(X_train, w, b)
print(np.shape(yhat_train))
yhat_train

(42000, 5)


array([[0.00162219, 0.41123093, 0.13369095, 0.24993993, 0.20351601],
       [0.27220607, 0.11279519, 0.22936655, 0.37261665, 0.01301554],
       [0.1318597 , 0.15773993, 0.0394456 , 0.49744499, 0.17350978],
       ...,
       [0.06795851, 0.23624866, 0.34945926, 0.13262757, 0.21370601],
       [0.38203653, 0.05555416, 0.30062698, 0.23846684, 0.02331549],
       [0.23419893, 0.08668333, 0.51245263, 0.11674884, 0.04991627]])

In [13]:
y_pred_train = predict_class(X_train, w, b)
print(np.shape(y_pred_train))
y_pred_train

(42000,)


array([1, 3, 3, ..., 2, 0, 2])

In [14]:
cost = softmax_cost(y_train, yhat_train)
cost

2.2582761074617936

In [15]:
n_iter = 1000
alpha = 1.5
w, b, cost_history = softmax_gradient_descent(X_train, w, b, y_train, n_iter, alpha, classes)

Cost at iteration 0: 2.2582761074617936
Cost at iteration 100: 0.5157423038653841
Cost at iteration 200: 0.5151050166745381
Cost at iteration 300: 0.5150688023682691
Cost at iteration 400: 0.5150657803643482
Cost at iteration 500: 0.5150654823538526
Cost at iteration 600: 0.5150654505461078
Cost at iteration 700: 0.5150654470239152
Cost at iteration 800: 0.5150654466272603
Cost at iteration 900: 0.5150654465822466
Cost at iteration 1000: 0.5150654465771352


In [16]:
cost_history[::n_iter//50]

array([2.25827611, 0.53742654, 0.52182188, 0.51785913, 0.51638882,
       0.5157423 , 0.51542904, 0.51526753, 0.51518064, 0.51513242,
       0.51510502, 0.51508914, 0.51507979, 0.51507422, 0.51507085,
       0.5150688 , 0.51506754, 0.51506676, 0.51506628, 0.51506597,
       0.51506578, 0.51506566, 0.51506558, 0.51506553, 0.5150655 ,
       0.51506548, 0.51506547, 0.51506546, 0.51506546, 0.51506545,
       0.51506545, 0.51506545, 0.51506545, 0.51506545, 0.51506545,
       0.51506545, 0.51506545, 0.51506545, 0.51506545, 0.51506545,
       0.51506545, 0.51506545, 0.51506545, 0.51506545, 0.51506545,
       0.51506545, 0.51506545, 0.51506545, 0.51506545, 0.51506545])

In [17]:
yhat_train = predict_softmax(X_train, w, b)
print(np.shape(yhat_train))
y_pred_train = softmax_to_class(yhat_train)
print(np.shape(y_pred_train))
y_pred_train

(42000, 5)
(42000,)


array([1, 2, 4, ..., 3, 2, 2])

In [18]:
mce_train = mce(y_train, y_pred_train)
mce_train

0.8345952380952381

In [19]:
pd.crosstab(y_train, y_pred_train, rownames = ['Actual'], colnames = ['Predicted'])

Predicted     0     1      2     3     4
Actual                                  
0          2003   152    223   753   408
1            59  9034    619    63   218
2            95   487  13095   679   200
3           306   248    946  7125   141
4           132   361    362   495  3796

In [20]:
f1_train_macro = macro_f1_multi(y_train, y_pred_train)
f1_train_macro

0.7972329899795796

In [21]:
print(one_f1_multi(y_train, y_pred_train, 0))
print(one_f1_multi(y_train, y_pred_train, 1))
print(one_f1_multi(y_train, y_pred_train, 2))
print(one_f1_multi(y_train, y_pred_train, 3))
print(one_f1_multi(y_train, y_pred_train, 4))

0.6530811868275187
0.8911467324290999
0.8788295694775343
0.7969352944466194
0.7661721667171257


In [22]:
f1_train_micro = micro_f1_multi(y_train, y_pred_train)
f1_train_micro

0.8345952380952382

## Cross-Validation

In [23]:
X_cv = np.array(df.iloc[42000:, 1:21])
m_cv, n_cv = np.shape(X_cv)
print(m_cv, n_cv)
print(X_cv[0,:])
X_cv,_,_ = lnr.normalize(X_cv, X_mean, X_std)

6000 20
[ -52.83098474  -16.27915175   85.35406271  114.75813282  101.16894289
  155.1107094   -28.92641771  -65.19447651  -87.5173925  -216.16653358
   35.23932044   50.02876754  118.49449128 -181.30508712   18.84293903
  -31.95344202  -47.03502965  -14.17431689  -35.81071028  -93.75549678]


In [24]:
y_cv = np.array(df.iloc[42000:, 21])
print(np.shape(y_cv))

(6000,)


In [25]:
yhat_cv = predict_softmax(X_cv, w, b)
print(np.shape(yhat_cv))
yhat_cv

(6000, 5)


array([[1.10658277e-01, 1.54865510e-03, 3.49407842e-02, 6.93603558e-01,
        1.59248725e-01],
       [8.09972799e-03, 5.64538016e-04, 7.82371097e-01, 1.39771159e-01,
        6.91934772e-02],
       [6.70534078e-04, 8.92383798e-01, 2.71002285e-02, 7.89643370e-02,
        8.81102061e-04],
       ...,
       [1.03936031e-03, 3.58254382e-01, 6.19612189e-01, 1.33814954e-02,
        7.71257307e-03],
       [1.16775093e-02, 9.08425687e-02, 9.66720500e-03, 8.80801457e-01,
        7.01126004e-03],
       [1.63064817e-01, 8.65248673e-02, 6.69755547e-01, 7.60068127e-02,
        4.64795615e-03]])

In [26]:
y_pred_cv = predict_class(X_cv, w, b)
print(np.shape(y_pred_cv))
y_pred_cv

(6000,)


array([3, 2, 1, ..., 2, 3, 2])

In [27]:
mce_cv = mce(y_cv, y_pred_cv)
mce_cv

0.8338333333333333

In [28]:
pd.crosstab(y_cv, y_pred_cv, rownames = ['Actual'], colnames = ['Predicted'])

Predicted    0     1     2     3    4
Actual                               
0          271    19    38   112   61
1           12  1262    89    17   31
2           12    66  1864    88   32
3           44    26   148  1065   15
4           19    67    44    57  541

In [29]:
f1_cv_macro = macro_f1_multi(y_cv, y_pred_cv)
f1_cv_macro

0.7941362546700111

In [30]:
f1_cv_micro = micro_f1_multi(y_cv, y_pred_cv)
f1_cv_micro

0.8338333333333332

# Testing Dataset

In [31]:
df_test = pd.read_csv("/datasets/multi_classification_test.csv")
df_test.head()

ID   Feature_1   Feature_2  Feature_3   Feature_4  Feature_5   Feature_6  \
0   1  -53.837350  -32.645889  88.656704   68.460038  77.278980  170.299440   
1   2  -72.698043  137.186526  85.122064 -135.777642  72.743374   37.159495   
2   3  -87.376758   52.292029  82.285036 -103.899819  76.276041   22.141478   
3   4 -114.053308  -82.064113  87.352300  311.645082  80.806755  158.822556   
4   5 -129.305845  -70.794135  87.318648  -39.995258  91.126015   96.496800   

    Feature_7   Feature_8   Feature_9  ...  Feature_11  Feature_12  \
0  -40.452999  157.171382   81.019740  ...   45.212220   79.052230   
1    1.219229   86.447392  -29.006295  ...   41.602345   68.546653   
2  131.322204   69.009157 -121.703035  ...   50.667553   94.928521   
3  -74.591773  254.856750 -279.480145  ...   63.089374  131.078916   
4    0.578289 -101.344881   17.968593  ...   -3.900131  -63.876158   

   Feature_13  Feature_14  Feature_15  Feature_16  Feature_17  Feature_18  \
0   23.209321 -300.397141  -26.927269   -7.724388  -47.897697  -31.844784   
1  103.288778    0.742860   31.342856   37.431942  -92.965704  -22.113709   
2   60.908583  -30.925963 -119.456062  170.920590   -8.940891  -49.424624   
3   13.590238    3.596146 -220.548262  -77.689231   21.423893  -64.062843   
4   27.123655   43.230208  -76.974733  -91.008909  -91.917865    1.852507   

   Feature_19  Feature_20  
0  -80.670098  -68.257050  
1  -57.311455  -74.076167  
2  -76.538002  -35.694483  
3  -69.416930  -12.109111  
4  -88.130343 -103.909397  

[5 rows x 21 columns]

In [32]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   ID          12000 non-null  int64  
 1   Feature_1   12000 non-null  float64
 2   Feature_2   12000 non-null  float64
 3   Feature_3   12000 non-null  float64
 4   Feature_4   12000 non-null  float64
 5   Feature_5   12000 non-null  float64
 6   Feature_6   12000 non-null  float64
 7   Feature_7   12000 non-null  float64
 8   Feature_8   12000 non-null  float64
 9   Feature_9   12000 non-null  float64
 10  Feature_10  12000 non-null  float64
 11  Feature_11  12000 non-null  float64
 12  Feature_12  12000 non-null  float64
 13  Feature_13  12000 non-null  float64
 14  Feature_14  12000 non-null  float64
 15  Feature_15  12000 non-null  float64
 16  Feature_16  12000 non-null  float64
 17  Feature_17  12000 non-null  float64
 18  Feature_18  12000 non-null  float64
 19  Feature_19  12000 non-nul

In [33]:
df_test.describe()

ID     Feature_1     Feature_2     Feature_3     Feature_4  \
count  12000.00000  12000.000000  12000.000000  12000.000000  12000.000000   
mean    6000.50000    -70.459672    -30.355190     86.067687     57.514598   
std     3464.24595     35.759288     64.329818      3.157463    149.130577   
min        1.00000   -213.058020   -283.716130     75.220211   -533.565640   
25%     3000.75000    -94.239923    -75.054623     83.844858    -40.402772   
50%     6000.50000    -70.086857    -33.926912     86.210125     62.728770   
75%     9000.25000    -47.321537     11.892735     88.277006    160.122910   
max    12000.00000     82.115039    214.503489     96.792019    576.002451   

          Feature_5     Feature_6     Feature_7     Feature_8     Feature_9  \
count  12000.000000  12000.000000  12000.000000  12000.000000  12000.000000   
mean      82.590908     76.676894     21.196872     24.156476    -58.761109   
std       20.950700     49.399047     83.759452    105.278654    102.839971   
min       -1.559606   -129.575846   -278.592709   -374.177999   -446.695214   
25%       68.324415     43.590525    -39.292537    -51.059563   -132.644786   
50%       82.527769     76.751042     20.049953     21.217907    -55.357303   
75%       96.457373    110.119247     82.060668     98.095862     14.352233   
max      172.934778    275.654035    306.381525    383.157331    308.666987   

       ...    Feature_11    Feature_12    Feature_13    Feature_14  \
count  ...  12000.000000  12000.000000  12000.000000  12000.000000   
mean   ...     35.708309     51.393635     72.489098    -64.896042   
std    ...     23.284913     67.764525     41.418180    106.389714   
min    ...    -60.790995   -229.441834    -83.731883   -433.597824   
25%    ...     18.780768      2.130545     42.043397   -141.546129   
50%    ...     35.417822     50.548250     71.458779    -67.777628   
75%    ...     52.763413    101.027962    102.678699     12.375553   
max    ...    121.545013    301.198448    221.859248    297.779767   

         Feature_15    Feature_16    Feature_17    Feature_18    Feature_19  \
count  12000.000000  12000.000000  12000.000000  12000.000000  12000.000000   
mean     -69.048678     15.150842    -54.394361    -35.236782    -94.643822   
std      110.810276     90.380964     58.859959     28.166417     36.147780   
min     -479.121591   -285.717333   -246.603075   -145.272325   -237.735701   
25%     -144.855133    -48.420176    -97.157457    -53.013372   -119.029839   
50%      -71.397598     10.932679    -53.556518    -33.474515    -94.528378   
75%        4.832864     74.879153    -11.888199    -15.966294    -69.791287   
max      348.813273    401.887266    136.317542     66.974819     58.375595   

         Feature_20  
count  12000.000000  
mean     -55.670561  
std       26.223483  
min     -172.305504  
25%      -72.058186  
50%      -52.813849  
75%      -37.172798  
max       29.565092  

[8 rows x 21 columns]

In [34]:
X_test = np.array(df_test.iloc[:, 1:21])
m_test, n_test = np.shape(X_test)
print(m_test, n_test)
print(X_test[0,:])
X_test,_,_ = lnr.normalize(X_test, X_mean, X_std)

12000 20
[ -53.83734971  -32.6458895    88.65670437   68.46003803   77.27898015
  170.2994399   -40.45299855  157.17138243   81.01974008  -86.62883712
   45.21222016   79.05223025   23.20932136 -300.39714084  -26.92726894
   -7.72438778  -47.8976972   -31.84478415  -80.67009828  -68.25705001]


In [35]:
yhat_test = predict_softmax(X_test, w, b)
print(np.shape(yhat_test))
yhat_test

(12000, 5)


array([[2.45733999e-02, 1.34351295e-03, 2.82054373e-01, 6.88857402e-01,
        3.17131238e-03],
       [2.51601655e-03, 9.90602384e-01, 2.41795753e-03, 2.26760805e-03,
        2.19603348e-03],
       [8.35817856e-04, 9.93362486e-01, 1.26803392e-03, 1.83187593e-03,
        2.70178665e-03],
       ...,
       [2.54098858e-02, 1.00828979e-01, 2.31509212e-02, 8.32145598e-01,
        1.84646158e-02],
       [5.61568301e-01, 2.47243715e-06, 3.13316912e-05, 2.15848152e-02,
        4.16813080e-01],
       [1.71210843e-04, 9.95646277e-01, 7.35194938e-04, 6.89712001e-04,
        2.75760506e-03]])

In [36]:
y_pred_test = predict_class(X_test, w, b)
print(np.shape(y_pred_test))
y_pred_test

(12000,)


array([3, 1, 1, ..., 3, 0, 1])